services:
  db:
    image: mysql:8.0
    container_name: finance-db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: finance-phpmyadmin
    env_file:
      - .env
    ports:
      - "${PMA_PORT}:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: finance-api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db_data: